<?php

/*
* Auto-generated by the function-mocker-le package with the `fmle generate:system command`
* on 2018-02-25 22:09:45
*/
class Foo implements \tad\FunctionMockerLe\System
{
    public function name()
    {
        return 'Foo';
    }
    public function setUp(...$args)
    {
        if (!function_exists('aFunction')) {
            \tad\FunctionMockerLe\define('aFunction', function ($arg1, $string2) {
                return;
            });
        }
    }
    public function tearDown()
    {
        \tad\FunctionMockerLe\undefineAll($this->defined());
    }
    public function defined()
    {
        return array('aFunction');
    }
}