<?php

namespace foo\bar;

/*
* Auto-generated by the function-mocker-le package with the `fmle generate:system command`
* on 2018-03-05 09:58:55
*/
class SystemTwo implements \tad\FunctionMockerLe\System
{
    public function name()
    {
        return 'SystemTwo';
    }
    public function setUp(...$args)
    {
        include_once __DIR__ . '/SystemTwo-functions.php';
    }
    public function tearDown()
    {
        \tad\FunctionMockerLe\undefineAll($this->defined());
    }
    public function defined()
    {
        return array('bFunction');
    }
}